# NOTE: This file is placed outside <PROJECT_NAME> directory, but inside a REPOSITORY directory 
# i.e. <PROJECT_NAME> directory and this YML file are at same level.
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@14.2.3
    echo ng --version
    ng --version
    npm install -g yarn
    cd <PROJECT_NAME>
    yarn install
    yarn build:ssr
  displayName: 'npm install and build'
